-- Tabela de controle de sincronização (Oracle)
CREATE TABLE tb_controle_sync_odontoprev (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_empresa VARCHAR2(6) NOT NULL,
    tipo_operacao VARCHAR2(10) NOT NULL CHECK (tipo_operacao IN ('CREATE', 'UPDATE', 'DELETE')),
    tipo_controle NUMBER(1) NOT NULL DEFAULT 1,
    endpoint_destino VARCHAR2(200) NOT NULL,
    dados_json CLOB,
    status_sync VARCHAR2(10) DEFAULT 'PENDING' CHECK (status_sync IN ('PENDING', 'SUCCESS', 'ERROR', 'RETRY')),
    tentativas NUMBER DEFAULT 0,
    max_tentativas NUMBER DEFAULT 3,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_ultima_tentativa TIMESTAMP,
    data_sucesso TIMESTAMP,
    erro_mensagem CLOB,
    response_api CLOB
);

-- Comentários nas colunas
COMMENT ON COLUMN tb_controle_sync_odontoprev.tipo_controle IS '1=Adição, 2=Alteração, 3=Exclusão';
COMMENT ON COLUMN tb_controle_sync_odontoprev.tipo_operacao IS 'CREATE, UPDATE ou DELETE';
COMMENT ON COLUMN tb_controle_sync_odontoprev.status_sync IS 'PENDING, SUCCESS, ERROR ou RETRY';

-- Índices para melhor performance
CREATE INDEX idx_empresa ON tb_controle_sync_odontoprev (codigo_empresa);
CREATE INDEX idx_status ON tb_controle_sync_odontoprev (status_sync);
CREATE INDEX idx_data_criacao ON tb_controle_sync_odontoprev (data_criacao);
CREATE INDEX idx_tipo_controle ON tb_controle_sync_odontoprev (tipo_controle);

CREATE VIEW vw_integracao_odontoprev AS
SELECT 
    -- Dados da Empresa
    e.codigo_empresa,
    e.cnpj,
    e.codigo_cliente_operadora,
    e.nome_fantasia,
    e.data_inicio_contrato,
    e.data_fim_contrato,
    e.data_vigencia,
    e.empresa_pf,
    e.codigo_grupo_gerencial,
    e.codigo_marca,
    e.codigo_celula,
    e.vidas_ativas,
    e.valor_ultimo_faturamento,
    e.sinistralidade,
    
    -- Dados dos Planos
    p.codigo_plano,
    p.descricao_plano,
    p.nome_fantasia_plano,
    p.numero_registro_ans,
    p.sigla_plano,
    p.valor_titular,
    p.valor_dependente,
    p.data_inicio_plano,
    p.data_fim_plano,
    p.co_participacao,
    p.tipo_negociacao,
    
    -- Dados de Tipos de Cobrança
    tc.codigo_tipo_cobranca,
    tc.nome_tipo_cobranca,
    tc.sigla_tipo_cobranca,
    tc.numero_banco,
    tc.nome_banco,
    tc.numero_parcelas
    
FROM empresas e
LEFT JOIN planos p ON e.codigo_empresa = p.codigo_empresa
LEFT JOIN tipos_cobranca tc ON e.codigo_empresa = tc.codigo_empresa
WHERE e.ativo = 1 -- Apenas empresas ativas